# Generated by Django 6.0.6 on 2026-06-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='experience',
            new_name='experience_years',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(max_length=255),
        ),
    ]
